### ISSUE TITLE
Have you repo of pkg gnome3 and all the deps like cmd (cinnamon)?

### ISSUE THREAD

**Issue by free-archer** [w41l/gnome#2]
Have you repo of pkg gnome3 and all the deps like cmd (cinnamon)?

**Comment by w41l** [comment]
Sorry, no. It's just a build script and sadly I don't have a time to updating it.

You can always fork and work on it if you want :-)

I think it will be easier to update using more recent gnome version if you are using slackware current because now slackware already including PAM. For session tracking you can use elogind, see https://alien.slackbook.org/blog/replacing-consolekit2-with-elogind-first-steps/
